### ISSUE TITLE
Host summary giving wrong timestamps (probably)

### ISSUE THREAD

**Issue by ghost** [dobrevg/webrsnapshot#1]
In the host summary screen the date column is giving the date of the path that's on the actual directory it's referencing. However, this date doesn't always change if something in the root of the backup hasn't changed. In my case it's essentially showing the date the folder for that host's backup was initially created. Here's my display:

![screen shot 2014-07-14 at 5 29 31 pm](https://cloud.githubusercontent.com/assets/5223569/3579095/1da50bca-0bb7-11e4-958b-16f4538316c2.png)

However, hourly.0-2 (the parents) have different timestamps which reflect the time the actual backup was made (when the cron ran):

drwxr-xr-x 6 root root 4096 Jul 14 17:11 hourly.0
drwxr-xr-x 6 root root 4096 Jul 14 16:39 hourly.1
drwxr-xr-x 6 root root 4096 Jul 14 16:36 hourly.2

Hopefully that makes sense. Maybe consider using the parent timestamp in the listing so the date and age columns are more accurate (reflecting when the cron jobs actually ran.)

Thanks!

**Comment by jangari** [comment]
I'm getting all my last change dates as 1/1/1970. I can't find where the issue might be:
![2016-05-31_16-07-32](https://cloud.githubusercontent.com/assets/1875291/15664780/e9efc5e4-2749-11e6-8c19-750674b8c28c.png)
Whereas the snapshots certainly have dates:
```
root@host:~/bin/webrsnapshot# ls -l /mnt/backups/
total 64
drwxr-xr-x 4 root root 4096 May 30 04:02 daily.0
drwxr-xr-x 4 root root 4096 May 29 04:02 daily.1
drwxr-xr-x 4 root root 4096 May 28 04:02 daily.2
drwxr-xr-x 4 root root 4096 May 27 04:02 daily.3
drwxr-xr-x 4 root root 4096 May 26 04:00 daily.4
drwxr-xr-x 4 root root 4096 May 25 04:00 daily.5
drwxr-xr-x 4 root root 4096 May 24 04:00 daily.6
```

Is this a related issue?

**Comment by dobrevg** [comment]
In Rsnapshot Config you have missing trailing slash "/" in the field 
"snapshot_root".

**Comment by jangari** [comment]
Aha!

I suspected it might have had something to do with that, but assumed it would probably fail elsewhere if it were a problem.

Thanks!
