### ISSUE TITLE
Exit: Config file missing: config/webrsnapshot.yml when running the script

### ISSUE THREAD

**Issue by akbar1989-sys** [dobrevg/webrsnapshot#6]
I have configured to run webrsnapshot but when I run it there is an error like this  [87081] [info] Exit: Config file missing: config/webrsnapshot.yml...?

**Comment by Root-Akbar89** [comment]
Server-Testing:/home/akbar/webrsnapshot/submodules/mojo/script#
PERL=$(which perl) && sed -i '1 s|^.*$|#!'"$PERL"'|'
/root./webrsnapshot/submodules/mojo/script/*


sed: can't read /root/webrsnapshot/submodules/mojo/script/*: No such file
or directory ---> In This Error

Pada Kam, 29 Des 2022 pukul 20.00 dobrevg ***@***.***>
menulis:

**Comment by Root-Akbar89** [comment]
In this error ***@***.***:/home/akbar#
./webrsnapshot/submodules/mojo/script/hypnotoad
./webrsnapshot/script/webrsnapshot
[2023-10-20 11:35:39.68694] [157957] [info] Exit: Config file missing:
config/webrsnapshot.yml

Pada Jum, 20 Okt 2023 pukul 11.29 Muhammad Akbar Abdullah <
***@***.***> menulis:
